# Generated by Django 3.1.1 on 2022-01-21 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokeagenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pokeagenda',
            name='imagem',
            field=models.URLField(max_length=999),
        ),
    ]
